version: '2.1'

services:
  mysql:
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    volumes:
      - ./mysql-volume:/var/lib/mysql
    healthcheck:
      test: "exit 0"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  hello-mentors-server:
    image: hello-mentors-server
    build: 
      context: .
      args:
        PORT: ${PORT}
        ENV: dev
    environment:
      NODE_ENV: development
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    command: npm run debug
    depends_on:
      mysql:
        condition: service_healthy