version: '2.1'

services:
  mysql:
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    volumes:
      - ./mysql-volume:/var/lib/mysql
    healthcheck:
      test: "exit 0"

  hello-mentors-server:
    image: hello-mentors-server
    build: .
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      mysql:
        condition: service_healthy